import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SideBar } from "./components/SideBar";
import "./globals.css";
// import StoreProvider from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-lg h-[100vh]`}
      >
        <div
          className="grid grid-cols-[100px_1fr]"
          style={{ height: "inherit" }}
        >
          {/* <StoreProvider> */}
          <SideBar />
          <div className="flex items-center justify-center min-w-96">
            {children}
          </div>
        </div>
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
